# Generated by Django 5.2 on 2025-04-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='size',
            field=models.JSONField(blank=True, default=dict, help_text="Dimensions in format {'width': 0, 'height': 0, 'unit': 'cm'}"),
        ),
    ]
