# Generated by Django 5.2 on 2025-04-28 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artist', '0002_initial'),
        ('artwork', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='artworkview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='favoriteartwork',
            name='artwork',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='artwork.artwork'),
        ),
        migrations.AddField(
            model_name='favoriteartwork',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='artist.artistprofile'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='tags',
            field=models.ManyToManyField(blank=True, to='artwork.tag'),
        ),
        migrations.AlterUniqueTogether(
            name='artworkview',
            unique_together={('user', 'artwork')},
        ),
        migrations.AlterUniqueTogether(
            name='favoriteartwork',
            unique_together={('user', 'artwork')},
        ),
    ]
