# Generated by Django 5.2 on 2025-04-29 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artworkview',
            options={'ordering': ['-viewed_at']},
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='image',
        ),
        migrations.AddField(
            model_name='artwork',
            name='images',
            field=models.JSONField(default=list, help_text='Array of image objects with url and public_id'),
        ),
    ]
