# Generated by Django 5.2 on 2025-04-27 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0004_artistprofile_facebook_artistprofile_is_verified_and_more'),
        ('artwork', '0002_artwork_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteArtwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='artwork.artwork')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='artist.artistprofile')),
            ],
            options={
                'unique_together': {('user', 'artwork')},
            },
        ),
    ]
