# Generated by Django 5.2 on 2025-04-29 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0003_alter_artworkview_options_remove_artwork_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artwork',
            old_name='images',
            new_name='image',
        ),
    ]
