# Generated by Django 5.2 on 2025-04-27 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0003_favoriteartwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
