# Generated by Django 5.2 on 2025-04-19 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0002_artistprofile_contact_email_artistprofile_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
