# Generated by Django 5.2 on 2025-04-27 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0003_artistprofile_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='tiktok',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='youtube',
            field=models.URLField(blank=True, null=True),
        ),
    ]
