# Generated by Django 5.2 on 2025-04-27 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0004_artistprofile_facebook_artistprofile_is_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistprofile',
            name='name',
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='first_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='last_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='artistprofile',
            name='bio',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='artistprofile',
            name='profile_picture',
            field=models.ImageField(default='', upload_to='artist_images/'),
        ),
    ]
