# Generated by Django 5.2 on 2025-04-19 07:35
from django.db import migrations

def create_default_roles(apps, schema_editor):
    Role = apps.get_model('users', 'Role')

    default_roles = ['ADMIN', 'SELLER', 'BUYER']
    for role in default_roles:
        Role.objects.get_or_create(name=role, defaults={'permissions': {}})

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),  
    ]

    operations = [
        migrations.RunPython(create_default_roles),
    ]
