# Generated by Django 5.2 on 2025-04-27 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_created_at_customuser_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='updated_at',
            new_name='updatedAt',
        ),
    ]
